@startuml



skinparam component {
  backgroundColor<<camunda>> Orange
  backgroundColor<<user>> Yellow
}

interface "Channel Message Acceptor" as CMA

package "Ingress Adapter" {
  [ Kafka ]
}

package "Core" {
  package "Receive" {
    CMA -down- [ PersistingChannelMessageAcceptor ]
  }
  package "Process" {
    BatchCorrelationService -down- [ CamundaBPMBatchCorrelationService ]
    [ BatchCorrelationProcessor ] --> BatchCorrelationService : use
    [ CamundaBPMBatchCorrelationService ] --> [ CamundaCorrelationEventFactoryRegistry ] : use
    [ CamundaCorrelationEventFactoryRegistry ] -down-> CamundaCorrelationEventFactory : use
  }
  package "Persistence" {
    MessagePersistenceService -down- [ DefaultMessagePersistenceService ]
    [ DefaultMessagePersistenceService ] --> MessageRepository : use
    [ DefaultMessagePersistenceService ] --> SingleMessageCorrelationStrategy : use
    MessageRepository -down- [ MyBatisRepository ]
  }
}

package "Application Components" {
  [ MyCamundaCorrelationEventFactory ] <<user>>
  [ MySingleMessageCorrelationStrategy ] <<user>>
  [ MyCamundaCorrelationEventFactory ] --> [ MySingleMessageCorrelationStrategy ] : use
}

package "Camunda Components" {
  [ Camunda Runtime Service ] <<camunda>>
  [ MyBatis ] <<camunda>>
  [ Camunda Runtime Service ] --down-> [ MyBatis ]
}

database "Database" {
  [ MESSAGE ]
}

[ MyBatisRepository ] --> [ MyBatis ] : use
[ PersistingChannelMessageAcceptor ] --> MessagePersistenceService : use
[ BatchCorrelationProcessor ] --> MessagePersistenceService : use

[ Kafka ] --> CMA
[ MyBatis ] <--> [ MESSAGE ]
[ CamundaBPMBatchCorrelationService ] -left-> [ Camunda Runtime Service ] : use
[ MyCamundaCorrelationEventFactory ] -down- CamundaCorrelationEventFactory : implement
[ MySingleMessageCorrelationStrategy ] -down- SingleMessageCorrelationStrategy : implement
@enduml
