CREATE TABLE COR_MESSAGE (
    ID                     VARCHAR2(64) UNIQUE NOT NULL,
    PAYLOAD_ENCODING       VARCHAR2(64) NOT NULL,
    PAYLOAD_TYPE_NAMESPACE VARCHAR2(128) NOT NULL,
    PAYLOAD_TYPE_NAME      VARCHAR2(128) NOT NULL,
    PAYLOAD_TYPE_REVISION  VARCHAR2(64),
    PAYLOAD                BINARY(1024),
    INSERTED               TIMESTAMP NOT NULL,
    TTL_DURATION           VARCHAR2(32),
    EXPIRATION             TIMESTAMP,
    RETRIES                INTEGER   NOT NULL,
    NEXT_RETRY             TIMESTAMP,
    ERROR                  CLOB(10000)
);
