spring:
  cloud:
    stream:
      function:
        definition: ingress-consumer
        bindings:
          ingress-consumer-in-0: correlate-ingress-binding

correlate:
  enabled: true
  channels:
    ingress:
      type: stream
      enabled: true

  batch:
    mode: fail_first # default fail_first -> 'all' will correlate one message after another, resulting in ignoring the order of receiving
    query:    # query scheduler
      pollInitialDelay: PT10S
      pollInterval: PT6S
    cleanup:  # cleanup of expired messages
      pollInitialDelay: PT1M
      pollInterval: PT1M
    cluster:
      enabled: true
      queuePollLockMostInterval: PT5M
  message:
    #        timeToLiveAsString: PT10S # errors during TTL seconds after receiving are ignored
    payloadEncoding: jackson  # our bytes are actually JSON written by Jackson.
  persistence:
    messageMaxRetries: 5 # default 100 -> will try to deliver 5 times at most
    messageFetchPageSize: 100 # default 100
  retry:
    retryMaxBackoffMinutes: 5 # default 180 -> maximum 5 minutes between retries
    retryBackoffBase: 5.0 # value in minutes default 2.0 -> base in the power of retry to calculate the next retry


