server:
  port: 8083

hotel:
  processing-delay: 5

correlate:
  enabled: false

camunda:
  bpm:
    enabled: false

spring:
  application:
    name: Kafka Hotel Example Service
  jpa:
    open-in-view: false
  cloud:
    stream:
      function:
        definition: hotelProcessor
        bindings:
          hotelProcessor-in-0: hotels-binding
          hotelProcessor-out-0: hotels-result-binding
      bindings:
        hotels-binding:
          destination: ${KAFKA_TOPIC_HOTEL:hotel}
          binder: hotels
          group: ${KAFKA_GROUP_ID}
        hotels-result-binding:
          destination: ${KAFKA_TOPIC_HOTEL_RESULT:correlate-ingres}
          binder: hotels
          group: ${KAFKA_GROUP_ID}
      binders:
        hotels:
          type: kafka
          defaultCandidate: false
          inheritEnvironment: false
          environment:
            spring:
              kafka:
                producer:
                  key-serializer: org.apache.kafka.common.serialization.StringSerializer
                  value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
                consumer:
                  key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
                  value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
              cloud:
                stream:
                  kafka:
                    binder:
                      autoCreateTopics: false
                      autoAddPartitions: false
                      brokers: ${KAFKA_BOOTSTRAP_SERVER_HOST:localhost}:${KAFKA_BOOTSTRAP_SERVER_PORT:9092}
                      configuration:
                        security.protocol: ${KAFKA_SECURITY_PROTOCOL_OVERRIDE:PLAINTEXT}
