flight:
  processing-delay: ${PROCESSING_DELAY:5}

server:
  port: 8081

axon:
  axonserver:
    servers: "${AXON_SERVER_HOST:axonserver}:8124"

spring:
  application:
    name: Axon Flight Example Service
  jpa:
    open-in-view: true
