services:

  axonserver:
    image: axoniq/axonserver:2025.0.2
    container_name: correlate-axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true
      - AXONIQ_AXONSERVER_STANDALONE=true

  hotel:
    image: io.holunda/hotel-axon:latest
    container_name: hotel_axon
    depends_on:
      - axonserver

  flight:
    image: io.holunda/flight-axon:latest
    container_name: flight_axon
    depends_on:
      - axonserver
