@startuml
'https://plantuml.com/sequence-diagram

autonumber

Client -> Reservation: Create Reservation

Reservation -> "Flight Service": Book Flight
Reservation -> "Hotel Service": Book Hotel
"Hotel Service" --> Reservation: Hotel Reservation Confirmed
"Flight Service" --> Reservation: Flight Reservation Confirmed

@enduml
